# Generated by Django 3.2 on 2021-05-30 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizEngine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='num_of_answers',
            field=models.IntegerField(help_text='value should be from 1 to 4', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
