# Generated by Django 3.2 on 2021-05-31 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizEngine', '0003_auto_20210531_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
