# Generated by Django 3.2 on 2021-06-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizEngine', '0008_alter_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
